/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVER_H_RPCGEN
#define _SERVER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct OneLn {
	int x1;
	int y1;
	int x2;
	int y2;
	long color;
};
typedef struct OneLn OneLn;

typedef struct ALine *Linep;

struct ALine {
	struct ALine *next;
	OneLn ln;
};
typedef struct ALine ALine;

struct ClientData {
	char boardnm[50];
	char xdisplaynm[50];
	char machinenm[50];
	int nprogram;
	int nversion;
	long color;
};
typedef struct ClientData ClientData;

struct AddLineArg {
	OneLn ln;
	ClientData clientdata;
};
typedef struct AddLineArg AddLineArg;

#define WhiteBoardServer 0x20000099
#define WhiteBoardServerVersion 1

#if defined(__STDC__) || defined(__cplusplus)
#define addclient 1
extern  int * addclient_1(ClientData *, CLIENT *);
extern  int * addclient_1_svc(ClientData *, struct svc_req *);
#define delclient 2
extern  int * delclient_1(ClientData *, CLIENT *);
extern  int * delclient_1_svc(ClientData *, struct svc_req *);
#define addline 3
extern  int * addline_1(AddLineArg *, CLIENT *);
extern  int * addline_1_svc(AddLineArg *, struct svc_req *);
#define sendallmylines 4
extern  Linep * sendallmylines_1(ClientData *, CLIENT *);
extern  Linep * sendallmylines_1_svc(ClientData *, struct svc_req *);
extern int whiteboardserver_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define addclient 1
extern  int * addclient_1();
extern  int * addclient_1_svc();
#define delclient 2
extern  int * delclient_1();
extern  int * delclient_1_svc();
#define addline 3
extern  int * addline_1();
extern  int * addline_1_svc();
#define sendallmylines 4
extern  Linep * sendallmylines_1();
extern  Linep * sendallmylines_1_svc();
extern int whiteboardserver_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_OneLn (XDR *, OneLn*);
extern  bool_t xdr_Linep (XDR *, Linep*);
extern  bool_t xdr_ALine (XDR *, ALine*);
extern  bool_t xdr_ClientData (XDR *, ClientData*);
extern  bool_t xdr_AddLineArg (XDR *, AddLineArg*);

#else /* K&R C */
extern bool_t xdr_OneLn ();
extern bool_t xdr_Linep ();
extern bool_t xdr_ALine ();
extern bool_t xdr_ClientData ();
extern bool_t xdr_AddLineArg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVER_H_RPCGEN */
